good

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,20 +1,28 @@
 #!/usr/bin/env bash
-# bash script to install nginx
+#Configures a brand new ubuntu machine, i.e installs nginx and configures it
 
-source_file='/usr/share/nginx/html/index.html'
-dest_file='/usr/share/nginx/html/index.txt'
+NGINX_CONFIG='/etc/nginx/sites-available/default'
+DEFAULT_ROOT='/var/www/html'
+NEW_ROOT='/usr/share/nginx/html'
+BACKUP_INDEX="${NEW_ROOT}/index.txt"
+INDEX_PAGE="${NEW_ROOT}/index.html"
 
 apt-get -y update
 apt-get -y install nginx
 
-# Update the Nginx default configuration file to reset root
-sed -i 's|root /var/www/html;|root /usr/share/nginx/html;|' /etc/nginx/sites-available/default
-
-#if source file exits, back it up
-if [ -e "$source_file" ]; then
-	mv "$source_file" "$dest_file"
+#Changes the root of the nginx server to NEW_ROOT
+if [ -e "$NGINX_CONFIG" ]; then
+        sed -i "s|root ${DEFAULT_ROOT}|root ${NEW_ROOT}|" "${NGINX_CONFIG}"
+else
+        echo "Missing configuration file" >&2
+        exit 1
 fi
-# Ensure the new root exists
-mkdir -p /usr/share/nginx/html
-echo "Hello World!" > /usr/share/nginx/html/index.html
+
+#Backup the default index page
+if [ -e "$INDEX_PAGE" ]; then
+        mv "$INDEX_PAGE" "$BACKUP_INDEX"
+fi
+
+echo "Hello World!" > "$INDEX_PAGE"
+
 service nginx restart
diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,9 +1,41 @@
 #!/usr/bin/env bash
-# bash script to make /redirect_me redirect to another site
+#configures a brand new ubuntu machine, i.e installs nginx and configures it
+
+NGINX_CONFIG='/etc/nginx/sites-available/default'
+DEFAULT_ROOT='/var/www/html'
+NEW_ROOT='/usr/share/nginx/html'
+BACKUP_INDEX="${NEW_ROOT}/index.txt"
+INDEX_PAGE="${NEW_ROOT}/index.html"
+ERROR_PAGE="${NEW_ROOT}/404.html"
+
 apt-get -y update
 apt-get -y install nginx
-mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
-echo "Hello World!" > /usr/share/nginx/html/index.html
-new_string=".rules\n\t\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n"
-sed -i "s/.rules/$new_string/" /etc/nginx/sites-available/default
+
+#Changes the root of the nginx server to NEW_ROOT
+if [ -e "$NGINX_CONFIG" ]; then
+        sed -i "s|root ${DEFAULT_ROOT}|root ${NEW_ROOT}|" "${NGINX_CONFIG}"
+else
+        echo "Missing configuration file" >&2
+        exit 1
+fi
+
+#Backup the default index page
+if [ -e "$INDEX_PAGE" ]; then
+        mv "$INDEX_PAGE" "$BACKUP_INDEX"
+fi
+
+echo "Hello World!" > "$INDEX_PAGE"
+echo "Ceci n'est pas une page" > "$ERROR_PAGE"
+
+#Permanently redirect /redirect_me
+sed -i '/server_name _;/!b;
+        a\
+\
+        # Add redirect for /redirect_me\
+\
+        location /redirect_me {\
+                rewrite ^ https://youtube.com permanent;\
+        }\
+' "$NGINX_CONFIG"
+
 service nginx restart
